//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponsCollections
    {
        public int CGIID { get; set; }
        public string status { get; set; }
        public Nullable<double> lmd_id { get; set; }
        public string store { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string code { get; set; }
        public string featured { get; set; }
        public Nullable<double> coupon_type { get; set; }
        public Nullable<double> listing_sticker { get; set; }
        public string url { get; set; }
        public string link { get; set; }
        public Nullable<double> coupon_txt { get; set; }
        public string categories { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<System.DateTime> listing_expiry_date { get; set; }
    }
}
